version: "2"

services:
  slave:
    image: mongo:4.0.6
    expose:
      - "27017"
    ports:
      - "27018:27017"
    restart: always
    volumes:
#      - ./config/mongo-keyfile:/opt/mongo/mongo-keyfile:ro
#      - ./config/hosts:/etc/hosts:ro
      - ./config:/opt/mongo
    #command: sh -c "sh /opt/mongo/deployment_scripts.sh"
    # "cat /opt/mongo/hosts >> /etc/hosts"
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_ADVERTISED_HOSTNAME}
#      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=${MONGODB_PRIMARY_HOST}
      - MONGODB_PRIMARY_ROOT_PASSWORD=${MONGODB_PRIMARY_ROOT_PASSWORD}
#      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      
      - MONGODB_ROOT_PASSWORD=${MONGODB_PRIMARY_ROOT_PASSWORD}
      - MONGODB_PRIMARY_ROOT_USER=${MONGODB_USERNAME}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_KEY}
#      - MONGODB_DATABASE=ars02
#      - MONGODB_PRIMARY_PORT_NUMBER=27017
#      - MONGODB_EXTRA_FLAGS=
      - MONGODB_PASSWORD=${MONGODB_PRIMARY_ROOT_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
#    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/opt/mongo/mongo-keyfile", "--replSet", "rs0" ]
#    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs0" ]
    entrypoint: [ "sh", "/opt/mongo/deployment_scripts.sh" ]